# --- CONFIGURACAO DO SPRING AI --- Groq
# Endereco do servidor do Groq
spring.ai.openai.base-url=https://api.groq.com/openai/v1

# Chave de autenticacaoo da minha conta no Groq
spring.ai.openai.api-key=${AI_API_KEY}

# Qual modelo de IA vai responder as perguntas em texto
spring.ai.openai.chat.options.model=openai/gpt-oss-20b